repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        # args: [source, /dev/null]
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0 # Use the latest stable version; update as necessary
    hooks:
      - id: yamlfmt
        # args: ["-d", "--require-document-start"]  # Optional arguments
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1 # Replace with the latest version; check the repo for updates
    hooks:
      - id: yamllint
        args: [-d, '{extends: default, rules: {line-length: {max: 120}}}'] # Optional: Customize rules
  - repo: local
    hooks:
      - id: bashate
        name: bashate
        description: This hook runs bashate for linting shell scripts
        entry: bashate
        language: python
        types: [shell, zsh]
      - id: alejandra
        name: Alejandra
        language: system
        description: Run Alejandra on .nix scripts
        entry: alejandra
        files: \.nix$
